// <auto-generated />
namespace OnlineExamBD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3rd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3rd));
        
        string IMigrationMetadata.Id
        {
            get { return "202109111720470_3rd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
